### ISSUE TITLE
Implement TRNG

### ISSUE THREAD

**Issue by mchack-work** [tillitis/qemu#1]
Implement the random number generator in the qemu model.

According to software.md there is:

- TRNG_NAME0
- TRNG_NAME1
- TRNG_VERSION
- TRNG_STATUS
- TRNG_SAMPLE_RATE
- TRNG_ENTROPY

`mta1_mkdf_mem.h` also says `MTA1_MKDF_MMIO_TRNG_STATUS_READY_BIT = 0,`.

Do we need real random data in the model? If so, do we just read from the host's random pool? If not, would, say returning 4 (number from a throw with fair dice) each time be OK?

In the software.md the firmware protocol includes CMD_TRNG_DATA and _STATUS. Do we really need those? I don't think so. If we want to get at the TRNG we can just write an app, right? I suggest we remove these from the document

**Comment by quite** [comment]
Se also https://github.com/tillitis/tillitis-key1/pull/17

**Comment by mchack-work** [comment]
Merged in qemu and tillitis-key1.
