### ISSUE TITLE
Implement TIMER

### ISSUE THREAD

**Issue by mchack-work** [tillitis/qemu#2]
Implement the timer in the qemu model of TK1.

According to `software.md` at least these MMIO addresses:

- TIMER_NAME0
- TIMER_NAME1
- TIMER_VERSION
- TIMER_CTRL
- TIMER_STATUS
- TIMER_PRESCALER
- TIMER_TIMER

Also update the software.md table!

**Comment by mchack-work** [comment]
First stab in branch timer.

No way to reset timer yet. Have to figure out how the `CTRL` works.

Don't know what STATUS is for yet, either.

**Comment by mchack-work** [comment]
https://github.com/tillitis/qemu/pull/5

https://github.com/tillitis/tillitis-key1/pull/27

**Comment by quite** [comment]
It's done!
