### ISSUE TITLE
Add reset support

### ISSUE THREAD

**Issue by mchack-work** [tillitis/qemu#23]
With https://github.com/tillitis/tillitis-key1/pull/242 a device app running on TKey will be able to reset the TKey. Qemu should, of course, match the hardware.

A write to TK1_MMIO_TK1_SYSTEM_RESET 0xff0001C0 should trigger the reset. It's not clear to me exactly what is being reset. Is all memory being reset, too?

To implement this in qemu, perhaps someone might want to revisit the old watchdog branch? Sadly not working. We probably have to figure out how to register  a reset function for the machine class.

https://github.com/tillitis/qemu/tree/watchdog

Maybe this will help?

https://www.qemu.org/docs/master/devel/reset.html

**Comment by dehanj** [comment]
#27
