### ISSUE TITLE
qemu: Does the rv32 support Zmmul?

### ISSUE THREAD

**Issue by mchack-work** [tillitis/qemu#8]
We want to go to Zmmul and not use division. What do we do with the qemu model? Does the qemu rv32 support Zmmul? Do we just pretend and use Zmmul when compiling? Is that OK?

**Comment by quite** [comment]
Our cpu setup code in QEMU uses `set_misa()` to set IMC (MISA is some way to dynamically (?) set ISA extensions of a cpu?). Looks like QEMU 7.2 will support setting ZMMUL in this way (but there is nothing before that).
